# Generated by Django 5.2.1 on 2025-05-20 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('est_handicap', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('nb_personnes', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('validee', models.BooleanField(default=False)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seances.seance')),
            ],
        ),
    ]
