# Generated by Django 5.2.1 on 2025-05-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'À traiter'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='en_attente', max_length=20)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seances.salle')),
            ],
        ),
    ]
